name: Battlefield
version: '1.0-SNAPSHOT'
main: top.mores.battlefield.Battlefield
api-version: '1.18'
authors: [ Mores ]
description: battle field
commands:
  bf:
    description: Battlefield main command
    usage: /bf